// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qkybzlzzfbumyczewssi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFreWJ6bHp6ZmJ1bXljemV3c3NpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NzQ1MzUsImV4cCI6MjA2NTU1MDUzNX0.QqgYpXkVl0DsoiKMoR81Nq5qg1BJzV6f2TLTynIf3-Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);